### ISSUE TITLE
Make sure OAuth refresh token is first obtained

### ISSUE THREAD

**Issue by Drumber** [Drumber/Kitsune#14]
There is a race condition when the access token is being updated and at the same time other API calls are being made which result in 401 errors.

We should wait for the OAuth token call to finish before making any other API calls.
 
Captured logs:
```logcat
AuthPreferences         io.github.drumber.kitsune  D  Parse and return access token stored as json.
AuthRepository          io.github.drumber.kitsune  D  Loaded stored access token.
AuthRepository          io.github.drumber.kitsune  D  Access token expires on 1693827852 (in seconds)
AuthRepository          io.github.drumber.kitsune  D  Refreshing access token...
okhttp.OkHttpClient     io.github.drumber.kitsune  I  --> POST https://kitsu.io/api/oauth/token (236-byte body)
okhttp.OkHttpClient     io.github.drumber.kitsune  I  <-- 200 https://kitsu.io/api/oauth/token (2560ms, unknown-length body)
okhttp.OkHttpClient     io.github.drumber.kitsune  I  --> GET https://kitsu.io/api/edge/anime?etc
AuthPreferences         io.github.drumber.kitsune  D  Converting access token to json and storing it in encrypted shared preferences.
okhttp.OkHttpClient     io.github.drumber.kitsune  I  <-- 401 https://kitsu.io/api/edge/anime?etc
MainFragmentViewModel   io.github.drumber.kitsune  E  Failed to load data.
							retrofit2.HttpException: HTTP 401 
							at retrofit2.KotlinExtensions$await$2$2.onResponse(KotlinExtensions.kt:53)
							at retrofit2.OkHttpCall$1.onResponse(OkHttpCall.java:161)
							at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:519)
```

**Comment by Drumber** [comment]
Should be fixed with the added okhttp authenticator interceptor in #26.
When a 401 response code is received, the interceptor should refresh the access token and the request will be re-called by okhttp.
